# Generated by Django 6.0.2 on 2026-02-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('pest_alert', 'Pest Alert'), ('weather', 'Weather Observation'), ('crop_condition', 'Crop Condition'), ('fertilizer', 'Fertilizer Tip'), ('general', 'General Insight')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
